### ISSUE TITLE
In the bitcask intro paper we see it being mentioned that bitcask is able to support datasets larger than 10 X system memory. I am trying to understand how?

### ISSUE THREAD

**Issue by weezy20** [basho/bitcask#271]
If I am understanding correctly, the `keydir` in memory hash table contains all keys and maps them to a structure that will contain the location of the actual value. But when the authors of the paper mention `10` times the dataset of system memory I don't quite get what they mean. Do they mean the sum of `values` or the number of keys? Surely it can't store more than keys worth `10x` system memory right?

**Comment by aef-** [comment]
It's vague but you can read it as the amount data in the data files. Or keys and their values. But it's not referring to the size of the `keydir`.

**Comment by weezy20** [comment]
Ah I think that answers all my questions. Thanks. Just to confirm, `keydir` does not and can not hold all keys in memory, as surely we can imagine the (number of keys * size of keys) well exceeding system memory. Right?

**Comment by aef-** [comment]
keydir will hold all keys. Imagine you were searching for a key that exists in a data file but not the keydir. You'd have to search every file, in order, until you found it. This can be a bottleneck. The optimization is to have a keydir, a data structure that exists only in-memory and that maps keys to where their values exist in the file system.

Let's say each key is 16 bytes. You could hold 62.5 million keys in just 1 gigabyte of available memory. In practice it'll be less since you need to store some other information with the key as described in the white paper.

I recommend reading the first part of Kleppman's _Designing Data-Intensive Applications_ to get primer on SSTables, LSM-trees and the like if you're interested in this stuff.

**Comment by weezy20** [comment]
Thanks again for the detailed response. Appreciate it.
